### ISSUE TITLE
tmid in DoublePGSE not defined

### ISSUE THREAD

**Issue by fachra** [jingrebeccali/SpinDoctor#1]
Hi,
I got an error when using a DoublePGSE sequence.
Error message: _Unrecognized function or variable 'tmid'._
https://github.com/jingrebeccali/SpinDoctor/blob/35b2b9c40070a534559aec581a7b3bdb5eda97ad/src/sequences/DoublePGSE.m#L31-L36

Possible correction:
```matlab
F = (t < d) .* t ...
    + (d <= t & t < D) .* d ...
    + (D <= t & t < D + d) .* ((D + d) - t) ...
    + (D + d <= t & t < D + 2*d) .* (t - (D + d)) ...
    + (D + 2*d <= t & t < 2*D + d) .* d ...
    + (2*D + d <= t) .* ((2*d + 2*D) - t);
```

By the way, the current DoublePGSE sequence consists of two PGSE sequences without a pause between them. Is it possible to put a pause with duration _tm_ between them?

Thanks,
Chengran

**Comment by TinDoan-1209** [comment]
Dear Chengran,

Thank you for your email.

Some the previous works, d-PGSE 's profile is defined as what you mentioned
in
https://github.com/jingrebeccali/SpinDoctor/blob/35b2b9c40070a534559aec581a7b3bdb5eda97ad/src/sequences/DoublePGSE.m#L31-L36

So the completing definition of d-PGSE is shown in 2 attached papers in
this email,
where t_m: is the mixing time and TE= delta+ 2*Delta+ t_m.

 For testing, we set t_m= OGSEPER = delta/ npervec. So if we chose OGSEPER
= 1 for d-PGSE, it means t_m = delta and TE= 2*delta +2*Delta.

Thank you so much.

Yours sincerely,

Đoàn Khánh Thành Tín.
Doan Khanh Thanh Tin.

**Comment by agdestein** [comment]
Thank you for the feedback. I have corrected the missing variable. DoublePGSE now also supports a pause between the two PGSE sequences, which is passed as a third argument to the constructor.

**Comment by fachra** [comment]
> Thank you for the feedback. I have corrected the missing variable. DoublePGSE now also supports a pause between the two PGSE sequences, which is passed as a third argument to the constructor.

Great! Thanks!
