### ISSUE TITLE
issues on time-dependent ADC of PGSE

### ISSUE THREAD

**Issue by LiuFan19** [jingrebeccali/SpinDoctor#4]
Hi,
I'm using SpinDoctor to study ADC‘s variation with diffusion time. I use PGSE and modify **delta** to change the diffusion time. When increasing **delta**, the diffusion time decreases (d = Delta - delta/3), and theoretically ADC should increase. However, the simulation showed an opposite result.

Here are the parameters for the geometry:
```
setup.geometry.cell_shape = "sphere"; 
setup.geometry.ncell = 15; 
setup.geometry.rmin = 15;
setup.geometry.rmax = 15; 
setup.geometry.dmin = 0.0;
setup.geometry.dmax = 0.2;
setup.geometry.deformation = [0; 0]; 
setup.geometry.include_in = false; 
setup.geometry.ecs_shape = "tight_wrap";            
setup.geometry.ecs_ratio = 0.2;  
```
All permeability parameters are set to zero.

Here are the parameters for the sequence:
```
setup.gradient.values = [0 100 500 1000 2000 3000 4000];
setup.gradient.values_type = "b";
setup.gradient.sequences = { 
    PGSE(1000, 10000)
    PGSE(5000, 10000)
}';
setup.gradient.directions = [1.0; 1.0; 1.0]; 
```

Experiment parameters:
```
setup.btpde.ode_solver = @ode15s;                       % ODE solver for BTPDE
setup.btpde.reltol = 1e-4;                              % Relative tolerance for ODE solver
setup.btpde.abstol = 1e-6;

setup.hadc.ode_solver = @ode15s;                        % ODE solver for HADC
setup.hadc.reltol = 1e-4;                               % Relative tolerance for ODE solver
setup.hadc.abstol = 1e-4;  
``` 

Results from HADC model are:
```
ADC_allcmpt_PGSE(1000, 10000) = 0.001042179
ADC_allcmpt_PGSE(5000, 10000) = 0.000968690
```

Results from btpde_fit are:
```
ADC_allcmpt_PGSE(1000, 10000) = 0.001026644
ADC_allcmpt_PGSE(5000, 10000) = 0.000961006
```

When I decrease **Delta** of PGSE or use CosOGSE to decrease the diffusion time, ADC decreases, which makes sense.

**Comment by AlexMcSD** [comment]
Apologies for the delay. I do not see an issue with the results here, can you explain further what the issue is?

The ADC is computed by fitting an approximation to the signal, by assuming that the protons are diffusing freely through a homogeneous medium. This approximation is not necessarily valid for geometries with low permeabilities as the protons are then not diffusing freely.
